[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on = "<C-y>"
# run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
run = ["plugin wl-clipboard"]
desc = "Yank file to the clipboard"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to the root of the current git repository"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = "plugin kdeconnect-send"
desc = "Send selected files via KDE Connect"

[[mgr.prepend_keymap]]
on = [ ".", "s" ]
run  = "plugin what-size"
desc = "Calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = ["c", "y"]
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on = [ "c", "p" ]
run = "plugin save-clipboard-to-file"
desc = "Paste clipboard content to file and hover after created" 

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "plugin lazygit"
desc = "run lazygit"
