"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = false
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]

[preview]
image_delay = 50

[opener]
extract = [
	{ run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[open]
prepend_rules = [
    { url = "*.{zip,tar,gz,xz,rar,7z,bz2,zst}", use = "extract" },
]

[plugin]
prepend_fetchers = [
    # Schema requires 'url' + 'run'. 'prio' is optional but good to have.
    { id = "git", url = "*",  run = "git", prio = "normal" },
    { id = "git", url = "*/", run = "git", prio = "normal" },
]

prepend_previewers = [
    # Schema requires 'mime' OR 'url'
    { mime = "application/bittorrent", run = "torrent-preview" },
    # Changed 'name' to 'url'
    { url = "*.{3mf,obj,pts,ply,stl,step,stp}", run = "f3d-preview" },
]

prepend_preloaders = [
    # Changed 'name' to 'url'
    { url = "*.{3mf,obj,pts,ply,stl,step,stp}", run = "f3d-preview" },
]

