"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# yazi.toml
[manager]
show_hidden = true
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[opener]
edit = [
	{ run = 'nvim "%*"', block = true, for = "windows" },
]
open = [
	{ run = 'nvim "%*"', block = true, for = "windows" },
]
open_pdf = [
    { run = 'sioyek "%*"', block = true, for = "windows" },
]


[open]
prepend_rules = [
    { name = "*.pdf", use = "open_pdf" }
]
